package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"os"

	"github.com/kubestellar/console/pkg/rewards"
)

func main() {
	content := "// THIS FILE IS GENERATED BY scripts/gen-tiers-ts.go. DO NOT EDIT.\n\n"
	content += "export interface ContributorLevel {\n"
	content += "  rank: number;\n"
	content += "  name: string;\n"
	content += "  icon: string;\n"
	content += "  minCoins: number;\n"
	content += "  color: string;\n"
	content += "  bgClass: string;\n"
	content += "  textClass: string;\n"
	content += "  borderClass: string;\n"
	content += "}\n\n"

	levelsJson, err := json.MarshalIndent(rewards.ContributorLevels, "", "  ")
	if err != nil {
		fmt.Printf("Error marshaling JSON: %v\n", err)
		os.Exit(1)
	}
	content += fmt.Sprintf("export const CONTRIBUTOR_LEVELS: ContributorLevel[] = %s;\n", string(levelsJson))

	err = ioutil.WriteFile("web/src/types/rewards.generated.ts", []byte(content), 0644)
	if err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated web/src/types/rewards.generated.ts")

	// Also generate for Netlify functions
	netlifyContent := "// THIS FILE IS GENERATED BY scripts/gen-tiers-ts.go. DO NOT EDIT.\n\n"
	netlifyContent += fmt.Sprintf("export const CONTRIBUTOR_LEVELS = %s;\n", string(levelsJson))
	err = ioutil.WriteFile("web/netlify/functions/rewards-tiers.generated.ts", []byte(netlifyContent), 0644)
	if err != nil {
		fmt.Printf("Error writing Netlify file: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated web/netlify/functions/rewards-tiers.generated.ts")
}
